# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default

variables:
  - name: trimkeys
    value: |
      Default:
  - name: environment
    value: 'DEV'
  - name: filter
    value: 'Cams:HttpGatekeeper:HttpGatekeeper:Modules:0:*'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


- task: AzureAppConfiguration@6
  inputs:
    azureSubscription: 'devopsTest'
    AppConfigurationEndpoint: 'https://appconfigrdno.azconfig.io'
    KeyFilter: "Default:$(filter)"
    TrimKeyPrefix: $(trimkeys)

- task: AzureAppConfiguration@6
  inputs:
    azureSubscription: 'devopsTest'
    AppConfigurationEndpoint: 'https://appconfigrdno.azconfig.io'
    Label: $(environment)
    KeyFilter: "Default:$(filter)"
    TrimKeyPrefix: $(trimkeys)

- task: AzureAppConfiguration@6
  inputs:
    azureSubscription: 'devopsTest'
    AppConfigurationEndpoint: 'https://appconfigrdno.azconfig.io'
    KeyFilter: $(filter)
    TrimKeyPrefix: $(trimkeys)

- task: AzureAppConfiguration@6
  inputs:
    azureSubscription: 'devopsTest'
    AppConfigurationEndpoint: 'https://appconfigrdno.azconfig.io'
    KeyFilter: $(filter)
    Label: $(environment)
    TrimKeyPrefix: $(trimkeys)

- bash: env

