# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

variables:
  - name: trimkeys_old
    value: |
      Cams:HttpGatekeeper:HttpGatekeeper:Modules:0:
      test:
    readonly: True
  - name: environment
    value: 'DEV'

- task: AzureAppConfiguration@6
  inputs:
    azureSubscription: 'devopsTest'
    AppConfigurationEndpoint: 'https://appconfigrdno.azconfig.io'
    KeyFilter: 'Cams:HttpGatekeeper:HttpGatekeeper:Modules:0:*'
    TrimKeyPrefix: ${trimkeys}

- task: AzureAppConfiguration@6
  inputs:
    azureSubscription: 'devopsTest'
    AppConfigurationEndpoint: 'https://appconfigrdno.azconfig.io'
    KeyFilter: 'Cams:HttpGatekeeper:HttpGatekeeper:Modules:0:*'
    Label: ${environment}
    TrimKeyPrefix: ${trimkeys}

- task: AzureAppConfiguration@6
  inputs:
    azureSubscription: 'devopsTest'
    AppConfigurationEndpoint: 'https://appconfigrdno.azconfig.io'
    KeyFilter: 'Default:Cams:HttpGatekeeper:HttpGatekeeper:Modules:0:*'
    TrimKeyPrefix: ${trimkeys}

- task: AzureAppConfiguration@6
  inputs:
    azureSubscription: 'devopsTest'
    AppConfigurationEndpoint: 'https://appconfigrdno.azconfig.io'
    KeyFilter: 'Default:Cams:HttpGatekeeper:HttpGatekeeper:Modules:0:*'
    Label: ${environment}
    TrimKeyPrefix: ${trimkeys}

- bash: env

